#pragma once

#include<core/preprocessor/bool_or.h>
#include<core/preprocessor/uint8_if.h>
#include<core/preprocessor/uint8_equal.h>
#include<core/preprocessor/uint8_is_zero.h>
#include<core/preprocessor/uint8_less.h>
#include<core/preprocessor/uint8_sub_n.h>
#include<core/preprocessor/uint8_add_n.h>
#include<core/preprocessor/uint8_div.h>
#include<core/preprocessor/seq_unpack.h>

//    for(...)       ->   A3D_PP_RANGE_CALL
//       call(...)   ->   A3D_PP_RANGE_CALL
//			for( uint i = start; i!= end; i++)
//				inner_call(i, end - i- 1, others... )

//if(  step == 0)
//  return;
//else  
//  A3D_PP_RANGE_INNER_CALL_CMP(...)
#define A3D_PP_RANGE_INNER_CALL(start, end, step, call, ...)                     \
			A3D_PP_INT_IF( step,                                                 \
				A3D_PP_RANGE_INNER_CALL_CMP,                                     \
				A3D_PP_RANGE_INNER_CALL_END)(start, end, step, call, __VA_ARGS__)

// for(int i=start; i<=end; ++i)
//      first ## i-1 ## suffix ## second ## i ## split
#define A3D_PP_RANGE_CHAIN_CALL(start, end, fn, split)            \
			A3D_PP_RANGE_INNER_CALL(start, end, 1,                \
				A3D_PP_RANGE_CALL_ANOTHER1, split, fn)

#define A3D_PP_RANGE_CALL_ANOTHER1(Index, _, split, fn)  A3D_PP_RANGE_CALL_ANOTHER2(A3D_PP_SUB1(Index),Index,split,fn)
#define A3D_PP_RANGE_CALL_ANOTHER2(ForeIndex, Index, Split, Fn) Fn(ForeIndex, Index, A3D_PP_UNPACK( Split ))
#define A3D_PP_RANGE_CALL_ANOTHER3(FN) FN

//return directly
#define A3D_PP_RANGE_INNER_CALL_END(...)

//if(start < end) 
//   call A3D_PP_RANGE_INNER_CALL_SMALL_TO_BIG(...)
//else        
//   call A3D_PP_RANGE_INNER_CALL_BIG_TO_SMALL(...)
#define A3D_PP_RANGE_INNER_CALL_CMP(start, end, step, call, ...)                            \
			A3D_PP_IF( A3D_PP_LESS(start, end),                                             \
				A3D_PP_RANGE_INNER_CALL_SMALL_TO_BIG,                                       \
				A3D_PP_RANGE_INNER_CALL_BIG_TO_SMALL)(start, end, step, call, __VA_ARGS__)  \

// do small to  big loop
#define A3D_PP_RANGE_INNER_CALL_SMALL_TO_BIG(start, end, step, call, ...)                   \
			A3D_PP_RANGE_INNER_CALL_CHECK_STEP(A3D_PP_SUB(end, start),                      \
				start, step, call, A3D_PP_ADD, __VA_ARGS__ )

// do big to small loop
#define A3D_PP_RANGE_INNER_CALL_BIG_TO_SMALL(start, end, step, call, ...)                 \
			A3D_PP_RANGE_INNER_CALL_CHECK_STEP( A3D_PP_SUB(start, end),                   \
				start, step, call, A3D_PP_SUB, __VA_ARGS__ )

// check step
// if(step ==1) 
//    start loop
// else
//    do count = count/step
#define A3D_PP_RANGE_INNER_CALL_CHECK_STEP(count, N, step, call, op, ...) \
			A3D_PP_IF(A3D_PP_SUB1(step),                                  \
				A3D_PP_RANGE_INNER_CALL_DIV_STEP,                         \
				A3D_PP_RANGE_INNER_CALL_LOOP_START)(                    \
					count, N, step, call, op, __VA_ARGS__)

// step not 1, count = count / step
#define A3D_PP_RANGE_INNER_CALL_DIV_STEP(count, N, step, call, op, ...)  \
			A3D_PP_RANGE_INNER_CALL_DIV_STEP_HELPER(A3D_PP_DIV(count,step), N, step, call, op, __VA_ARGS__)
// evalute div
#define A3D_PP_RANGE_INNER_CALL_DIV_STEP_HELPER(count, N, step, call, op, ...) \
			A3D_PP_RANGE_INNER_CALL_LOOP_START(count, N, step, call, op, __VA_ARGS__)

// start loop
#define A3D_PP_RANGE_INNER_CALL_LOOP_START(count, N, step, call, op, ...) \
			A3D_PP_RANGE_INNER_CALL_LOOP##count(N, step, call, op, __VA_ARGS__)

#define A3D_PP_RANGE_INNER_CALL_CONNECT(x, y) A3D_PP_RANGE_INNER_CALL_CONNECT_STEP(x y)
#define A3D_PP_RANGE_INNER_CALL_CONNECT_STEP(result ) result

#define A3D_PP_RANGE_INNER_CALL_LOOP0(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 0, __VA_ARGS__))
#define A3D_PP_RANGE_INNER_CALL_LOOP1(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 1, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP0( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP2(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 2, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP1( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP3(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 3, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP2( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP4(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 4, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP3( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP5(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 5, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP4( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP6(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 6, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP5( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP7(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 7, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP6( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP8(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 8, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP7( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP9(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 9, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP8( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP10(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 10, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP9( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP11(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 11, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP10( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP12(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 12, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP11( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP13(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 13, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP12( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP14(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 14, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP13( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP15(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 15, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP14( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP16(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 16, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP15( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP17(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 17, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP16( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP18(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 18, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP17( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP19(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 19, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP18( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP20(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 20, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP19( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP21(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 21, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP20( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP22(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 22, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP21( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP23(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 23, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP22( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP24(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 24, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP23( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP25(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 25, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP24( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP26(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 26, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP25( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP27(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 27, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP26( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP28(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 28, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP27( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP29(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 29, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP28( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP30(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 30, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP29( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP31(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 31, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP30( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP32(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 32, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP31( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP33(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 33, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP32( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP34(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 34, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP33( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP35(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 35, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP34( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP36(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 36, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP35( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP37(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 37, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP36( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP38(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 38, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP37( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP39(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 39, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP38( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP40(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 40, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP39( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP41(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 41, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP40( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP42(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 42, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP41( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP43(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 43, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP42( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP44(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 44, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP43( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP45(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 45, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP44( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP46(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 46, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP45( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP47(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 47, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP46( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP48(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 48, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP47( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP49(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 49, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP48( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP50(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 50, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP49( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP51(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 51, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP50( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP52(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 52, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP51( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP53(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 53, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP52( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP54(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 54, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP53( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP55(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 55, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP54( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP56(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 56, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP55( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP57(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 57, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP56( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP58(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 58, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP57( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP59(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 59, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP58( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP60(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 60, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP59( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP61(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 61, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP60( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP62(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 62, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP61( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP63(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 63, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP62( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP64(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 64, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP63( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP65(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 65, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP64( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP66(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 66, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP65( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP67(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 67, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP66( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP68(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 68, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP67( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP69(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 69, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP68( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP70(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 70, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP69( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP71(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 71, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP70( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP72(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 72, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP71( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP73(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 73, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP72( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP74(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 74, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP73( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP75(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 75, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP74( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP76(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 76, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP75( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP77(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 77, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP76( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP78(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 78, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP77( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP79(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 79, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP78( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP80(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 80, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP79( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP81(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 81, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP80( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP82(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 82, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP81( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP83(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 83, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP82( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP84(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 84, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP83( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP85(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 85, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP84( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP86(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 86, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP85( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP87(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 87, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP86( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP88(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 88, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP87( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP89(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 89, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP88( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP90(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 90, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP89( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP91(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 91, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP90( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP92(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 92, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP91( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP93(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 93, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP92( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP94(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 94, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP93( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP95(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 95, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP94( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP96(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 96, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP95( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP97(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 97, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP96( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP98(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 98, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP97( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP99(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 99, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP98( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP100(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 100, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP99( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP101(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 101, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP100( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP102(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 102, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP101( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP103(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 103, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP102( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP104(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 104, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP103( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP105(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 105, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP104( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP106(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 106, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP105( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP107(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 107, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP106( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP108(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 108, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP107( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP109(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 109, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP108( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP110(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 110, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP109( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP111(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 111, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP110( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP112(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 112, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP111( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP113(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 113, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP112( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP114(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 114, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP113( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP115(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 115, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP114( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP116(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 116, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP115( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP117(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 117, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP116( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP118(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 118, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP117( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP119(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 119, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP118( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP120(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 120, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP119( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP121(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 121, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP120( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP122(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 122, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP121( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP123(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 123, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP122( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP124(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 124, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP123( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP125(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 125, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP124( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP126(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 126, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP125( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP127(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 127, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP126( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP128(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 128, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP127( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP129(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 129, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP128( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP130(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 130, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP129( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP131(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 131, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP130( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP132(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 132, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP131( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP133(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 133, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP132( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP134(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 134, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP133( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP135(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 135, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP134( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP136(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 136, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP135( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP137(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 137, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP136( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP138(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 138, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP137( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP139(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 139, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP138( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP140(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 140, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP139( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP141(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 141, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP140( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP142(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 142, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP141( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP143(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 143, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP142( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP144(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 144, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP143( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP145(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 145, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP144( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP146(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 146, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP145( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP147(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 147, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP146( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP148(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 148, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP147( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP149(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 149, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP148( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP150(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 150, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP149( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP151(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 151, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP150( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP152(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 152, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP151( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP153(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 153, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP152( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP154(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 154, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP153( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP155(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 155, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP154( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP156(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 156, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP155( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP157(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 157, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP156( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP158(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 158, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP157( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP159(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 159, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP158( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP160(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 160, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP159( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP161(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 161, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP160( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP162(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 162, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP161( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP163(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 163, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP162( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP164(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 164, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP163( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP165(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 165, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP164( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP166(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 166, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP165( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP167(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 167, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP166( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP168(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 168, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP167( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP169(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 169, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP168( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP170(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 170, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP169( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP171(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 171, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP170( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP172(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 172, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP171( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP173(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 173, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP172( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP174(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 174, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP173( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP175(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 175, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP174( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP176(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 176, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP175( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP177(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 177, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP176( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP178(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 178, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP177( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP179(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 179, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP178( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP180(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 180, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP179( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP181(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 181, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP180( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP182(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 182, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP181( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP183(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 183, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP182( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP184(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 184, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP183( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP185(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 185, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP184( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP186(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 186, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP185( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP187(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 187, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP186( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP188(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 188, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP187( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP189(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 189, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP188( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP190(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 190, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP189( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP191(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 191, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP190( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP192(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 192, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP191( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP193(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 193, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP192( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP194(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 194, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP193( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP195(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 195, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP194( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP196(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 196, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP195( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP197(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 197, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP196( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP198(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 198, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP197( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP199(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 199, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP198( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP200(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 200, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP199( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP201(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 201, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP200( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP202(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 202, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP201( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP203(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 203, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP202( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP204(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 204, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP203( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP205(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 205, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP204( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP206(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 206, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP205( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP207(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 207, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP206( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP208(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 208, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP207( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP209(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 209, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP208( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP210(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 210, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP209( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP211(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 211, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP210( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP212(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 212, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP211( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP213(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 213, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP212( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP214(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 214, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP213( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP215(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 215, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP214( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP216(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 216, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP215( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP217(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 217, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP216( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP218(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 218, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP217( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP219(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 219, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP218( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP220(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 220, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP219( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP221(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 221, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP220( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP222(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 222, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP221( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP223(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 223, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP222( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP224(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 224, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP223( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP225(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 225, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP224( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP226(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 226, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP225( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP227(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 227, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP226( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP228(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 228, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP227( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP229(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 229, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP228( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP230(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 230, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP229( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP231(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 231, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP230( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP232(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 232, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP231( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP233(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 233, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP232( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP234(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 234, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP233( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP235(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 235, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP234( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP236(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 236, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP235( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP237(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 237, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP236( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP238(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 238, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP237( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP239(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 239, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP238( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP240(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 240, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP239( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP241(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 241, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP240( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP242(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 242, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP241( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP243(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 243, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP242( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP244(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 244, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP243( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP245(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 245, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP244( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP246(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 246, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP245( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP247(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 247, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP246( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP248(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 248, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP247( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP249(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 249, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP248( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP250(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 250, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP249( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP251(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 251, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP250( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP252(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 252, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP251( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP253(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 253, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP252( op(N, step), step, call, op, __VA_ARGS__)
#define A3D_PP_RANGE_INNER_CALL_LOOP254(N, step, call, op, ...)   A3D_PP_RANGE_INNER_CALL_CONNECT(call,(N, 254, __VA_ARGS__))  A3D_PP_RANGE_INNER_CALL_LOOP253( op(N, step), step, call, op, __VA_ARGS__)
