#pragma once

#include<core/preprocessor/seq_size.h>
#include<core/preprocessor/seq_at.h>

//seq max length 63
#define A3D_PP_FOREACH_ITEM(call, seq, ...)             A3D_PP_FOREACH_ITEM_STEP1(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_STEP1(seq, call, ...)       A3D_PP_FOREACH_ITEM_STEP2(seq, call, A3D_PP_SIZE(seq), __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_STEP2(seq, call, size, ...) A3D_PP_FOREACH_ITEM_STEP3(seq, call, size, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_STEP3(seq, call, size, ...) A3D_PP_FOREACH_ITEM_VALUE##size (seq, call, __VA_ARGS__)

#define A3D_PP_FOREACH_ITEM_VALUE1(seq, call, ...)  call ( A3D_PP_AT(seq, 0), __VA_ARGS__ )
#define A3D_PP_FOREACH_ITEM_VALUE2(seq, call, ...)  call ( A3D_PP_AT(seq, 1), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE1(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE3(seq, call, ...)  call ( A3D_PP_AT(seq, 2), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE2(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE4(seq, call, ...)  call ( A3D_PP_AT(seq, 3), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE3(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE5(seq, call, ...)  call ( A3D_PP_AT(seq, 4), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE4(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE6(seq, call, ...)  call ( A3D_PP_AT(seq, 5), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE5(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE7(seq, call, ...)  call ( A3D_PP_AT(seq, 6), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE6(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE8(seq, call, ...)  call ( A3D_PP_AT(seq, 7), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE7(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE9(seq, call, ...)  call ( A3D_PP_AT(seq, 8), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE8(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE10(seq, call, ...) call ( A3D_PP_AT(seq, 9), __VA_ARGS__ )  A3D_PP_FOREACH_ITEM_VALUE9(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE11(seq, call, ...) call ( A3D_PP_AT(seq, 10), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE10(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE12(seq, call, ...) call ( A3D_PP_AT(seq, 11), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE11(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE13(seq, call, ...) call ( A3D_PP_AT(seq, 12), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE12(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE14(seq, call, ...) call ( A3D_PP_AT(seq, 13), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE13(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE15(seq, call, ...) call ( A3D_PP_AT(seq, 14), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE14(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE16(seq, call, ...) call ( A3D_PP_AT(seq, 15), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE15(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE17(seq, call, ...) call ( A3D_PP_AT(seq, 16), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE16(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE18(seq, call, ...) call ( A3D_PP_AT(seq, 17), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE17(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE19(seq, call, ...) call ( A3D_PP_AT(seq, 18), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE18(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE20(seq, call, ...) call ( A3D_PP_AT(seq, 19), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE19(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE21(seq, call, ...) call ( A3D_PP_AT(seq, 20), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE20(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE22(seq, call, ...) call ( A3D_PP_AT(seq, 21), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE21(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE23(seq, call, ...) call ( A3D_PP_AT(seq, 22), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE22(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE24(seq, call, ...) call ( A3D_PP_AT(seq, 23), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE23(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE25(seq, call, ...) call ( A3D_PP_AT(seq, 24), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE24(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE26(seq, call, ...) call ( A3D_PP_AT(seq, 25), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE25(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE27(seq, call, ...) call ( A3D_PP_AT(seq, 26), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE26(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE28(seq, call, ...) call ( A3D_PP_AT(seq, 27), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE27(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE29(seq, call, ...) call ( A3D_PP_AT(seq, 28), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE28(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE30(seq, call, ...) call ( A3D_PP_AT(seq, 29), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE29(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE31(seq, call, ...) call ( A3D_PP_AT(seq, 30), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE30(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE32(seq, call, ...) call ( A3D_PP_AT(seq, 31), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE31(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE33(seq, call, ...) call ( A3D_PP_AT(seq, 32), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE32(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE34(seq, call, ...) call ( A3D_PP_AT(seq, 33), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE33(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE35(seq, call, ...) call ( A3D_PP_AT(seq, 34), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE34(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE36(seq, call, ...) call ( A3D_PP_AT(seq, 35), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE35(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE37(seq, call, ...) call ( A3D_PP_AT(seq, 36), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE36(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE38(seq, call, ...) call ( A3D_PP_AT(seq, 37), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE37(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE39(seq, call, ...) call ( A3D_PP_AT(seq, 38), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE38(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE40(seq, call, ...) call ( A3D_PP_AT(seq, 39), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE39(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE41(seq, call, ...) call ( A3D_PP_AT(seq, 40), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE40(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE42(seq, call, ...) call ( A3D_PP_AT(seq, 41), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE41(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE43(seq, call, ...) call ( A3D_PP_AT(seq, 42), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE42(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE44(seq, call, ...) call ( A3D_PP_AT(seq, 43), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE43(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE45(seq, call, ...) call ( A3D_PP_AT(seq, 44), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE44(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE46(seq, call, ...) call ( A3D_PP_AT(seq, 45), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE45(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE47(seq, call, ...) call ( A3D_PP_AT(seq, 46), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE46(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE48(seq, call, ...) call ( A3D_PP_AT(seq, 47), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE47(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE49(seq, call, ...) call ( A3D_PP_AT(seq, 48), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE48(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE50(seq, call, ...) call ( A3D_PP_AT(seq, 49), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE49(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE51(seq, call, ...) call ( A3D_PP_AT(seq, 50), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE50(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE52(seq, call, ...) call ( A3D_PP_AT(seq, 51), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE51(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE53(seq, call, ...) call ( A3D_PP_AT(seq, 52), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE52(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE54(seq, call, ...) call ( A3D_PP_AT(seq, 53), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE53(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE55(seq, call, ...) call ( A3D_PP_AT(seq, 54), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE54(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE56(seq, call, ...) call ( A3D_PP_AT(seq, 55), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE55(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE57(seq, call, ...) call ( A3D_PP_AT(seq, 56), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE56(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE58(seq, call, ...) call ( A3D_PP_AT(seq, 57), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE57(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE59(seq, call, ...) call ( A3D_PP_AT(seq, 58), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE58(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE60(seq, call, ...) call ( A3D_PP_AT(seq, 59), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE59(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE61(seq, call, ...) call ( A3D_PP_AT(seq, 60), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE60(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE62(seq, call, ...) call ( A3D_PP_AT(seq, 61), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE61(seq, call, __VA_ARGS__)
#define A3D_PP_FOREACH_ITEM_VALUE63(seq, call, ...) call ( A3D_PP_AT(seq, 62), __VA_ARGS__ ) A3D_PP_FOREACH_ITEM_VALUE62(seq, call, __VA_ARGS__)
