#pragma once

#include<ccdk/type.h>
//type traits base lib
#include<ccdk/mpl/base/bool_.h>
#include<ccdk/mpl/base/and_.h>
#include<ccdk/mpl/base/or_.h>
#include<ccdk/mpl/base/when.h>
//add remove type traits
#include<ccdk/mpl/type_traits/add_const.h>
#include<ccdk/mpl/type_traits/add_const.h>
#include<ccdk/mpl/type_traits/add_volatile.h>
#include<ccdk/mpl/type_traits/add_cv.h>
#include<ccdk/mpl/type_traits/add_lref.h>
#include<ccdk/mpl/type_traits/add_rref.h>
#include<ccdk/mpl/type_traits/add_top_const.h>
#include<ccdk/mpl/type_traits/add_signed.h>
#include<ccdk/mpl/type_traits/add_unsigned.h>
#include<ccdk/mpl/type_traits/add_pointer.h>
#include<ccdk/mpl/type_traits/decay.h>
#include<ccdk/mpl/type_traits/align_of.h>
#include<ccdk/mpl/type_traits/array_dim.h>
#include<ccdk/mpl/type_traits/array_length.h>
#include<ccdk/mpl/type_traits/remove_all_dim.h>
#include<ccdk/mpl/type_traits/remove_dim.h>
#include<ccdk/mpl/type_traits/remove_const.h>
#include<ccdk/mpl/type_traits/remove_cv.h>
#include<ccdk/mpl/type_traits/remove_pointer.h>
#include<ccdk/mpl/type_traits/remove_ref.h>
#include<ccdk/mpl/type_traits/remove_top_const.h>
#include<ccdk/mpl/type_traits/remove_volatile.h>
#include<ccdk/mpl/type_traits/declval.h>
#include<ccdk/mpl/debug_type.hpp>

#include<ccdk/mpl/base/when.h>
#include<ccdk/mpl/base/index_sequence.h>
#include<ccdk/mpl/container/tuple.h>

#include<ccdk/mpl/type_traits/forward.h>
#include<ccdk/mpl/type_traits/move.h>
//is_xx type traits
#include<ccdk/mpl/type_traits/is_void.h>
#include<ccdk/mpl/type_traits/is_same.h>
#include<ccdk/mpl/type_traits/is_unsigned.h>
#include<ccdk/mpl/type_traits/is_signed.h>
#include<ccdk/mpl/type_traits/is_union.h>
#include<ccdk/mpl/type_traits/is_trivial.h>
#include<ccdk/mpl/type_traits/is_stand_layout.h>
#include<ccdk/mpl/type_traits/is_scalar.h>
#include<ccdk/mpl/type_traits/is_rref.h>
#include<ccdk/mpl/type_traits/is_lref.h>
#include<ccdk/mpl/type_traits/is_ref.h>
#include<ccdk/mpl/type_traits/is_polymorphic.h>
#include<ccdk/mpl/type_traits/is_pointer.h>
#include<ccdk/mpl/type_traits/is_pod.h>
#include<ccdk/mpl/type_traits/is_object.h>
#include<ccdk/mpl/type_traits/is_nullptr_t.h>
#include<ccdk/mpl/type_traits/is_mobj_ptr.h>
#include<ccdk/mpl/type_traits/is_mfn_ptr.h>
#include<ccdk/mpl/type_traits/is_member_ptr.h>
#include<ccdk/mpl/type_traits/is_integer.h>
#include<ccdk/mpl/type_traits/is_fundamental.h>
#include<ccdk/mpl/type_traits/is_function.h>
#include<ccdk/mpl/type_traits/is_float.h>
#include<ccdk/mpl/type_traits/is_final.h>
#include<ccdk/mpl/type_traits/is_enum.h>
#include<ccdk/mpl/type_traits/is_empty.h>
#include<ccdk/mpl/type_traits/is_scalar.h>
#include<ccdk/mpl/type_traits/is_compatible.h>
#include<ccdk/mpl/type_traits/is_const.h>
#include<ccdk/mpl/type_traits/is_compound.h>
#include<ccdk/mpl/type_traits/is_class.h>
#include<ccdk/mpl/type_traits/is_base_same.h>
#include<ccdk/mpl/type_traits/is_base_of.h>
#include<ccdk/mpl/type_traits/is_array.h>
#include<ccdk/mpl/type_traits/is_arithmetic.h>
#include<ccdk/mpl/type_traits/is_abstract.h>
#include<ccdk/mpl/type_traits/is_instance_of.h>
#include<ccdk/mpl/type_traits/is_compatible.h>
#include<ccdk/mpl/type_traits/is_convertible.h>
//has_xx type traits
#include<ccdk/mpl/type_traits/has_constructor.h>
#include<ccdk/mpl/type_traits/has_destructor.h>
#include<ccdk/mpl/type_traits/has_assigner.h>
#include<ccdk/mpl/type_traits/has_add.h>
#include<ccdk/mpl/type_traits/has_sub.h>
#include<ccdk/mpl/type_traits/has_mul.h>
#include<ccdk/mpl/type_traits/has_div.h>
#include<ccdk/mpl/type_traits/has_mod.h>
#include<ccdk/mpl/type_traits/has_bit_or.h>
#include<ccdk/mpl/type_traits/has_bit_and.h>
#include<ccdk/mpl/type_traits/has_bit_xor.h>
#include<ccdk/mpl/type_traits/has_shl.h>
#include<ccdk/mpl/type_traits/has_shr.h>
#include<ccdk/mpl/type_traits/has_lequal.h>
#include<ccdk/mpl/type_traits/has_nequal.h>
#include<ccdk/mpl/type_traits/has_gequal.h>
#include<ccdk/mpl/type_traits/has_equal.h>
#include<ccdk/mpl/type_traits/has_less.h>
#include<ccdk/mpl/type_traits/has_greater.h>
#include<ccdk/mpl/type_traits/has_logic_and.h>
#include<ccdk/mpl/type_traits/has_logic_or.h>
#include<ccdk/mpl/type_traits/has_front_dec.h>
#include<ccdk/mpl/type_traits/has_front_inc.h>
#include<ccdk/mpl/type_traits/has_post_dec.h>
#include<ccdk/mpl/type_traits/has_post_inc.h>
#include<ccdk/mpl/type_traits/has_bit_reverse.h>
#include<ccdk/mpl/type_traits/has_positive.h>
#include<ccdk/mpl/type_traits/has_negative.h>
#include<ccdk/mpl/type_traits/has_deref.h>
#include<ccdk/mpl/type_traits/has_logic_not.h>
#include<ccdk/mpl/type_traits/has_delete.h>
#include<ccdk/mpl/type_traits/has_new.h>
#include<ccdk/mpl/type_traits/has_indexer.h>
#include<ccdk/mpl/type_traits/has_invoker.h>
#include<ccdk/mpl/type_traits/has_arrow.h>
#include<ccdk/mpl/type_traits/has_inner_type.h>