#pragma once

#define CCDK_PP_BOOL_LESS(x, y)      CCDK_PP_BOOL_LESS_FAST(x,y)
#define CCDK_PP_BOOL_LESS_FAST(x, y) CCDK_PP_BOOL_LESS_VALUE##x##y
#define CCDK_PP_BOOL_LESS_VALUE00  0
#define CCDK_PP_BOOL_LESS_VALUE01  1
#define CCDK_PP_BOOL_LESS_VALUE10  0
#define CCDK_PP_BOOL_LESS_VALUE11  0
